from fpdf import FPDF
import markdown
import re

class PDFExporter:
    """
    Handles exporting chat responses to PDF.
    """
    
    @staticmethod
    def generate_chat_pdf(question, answer):
        """
        Generate a PDF containing the question and its answer.
        """
        pdf = FPDF()
        pdf.add_page()
        
        # Add Header
        pdf.set_font("helvetica", "B", 16)
        pdf.set_text_color(26, 35, 126) # Blue
        pdf.cell(0, 10, "DocQuery Analysis Report", ln=True, align="C")
        pdf.ln(10)
        
        # Question Section
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(33, 150, 243) # User blue
        pdf.cell(0, 10, "Question:", ln=True)
        
        pdf.set_font("helvetica", "", 11)
        pdf.set_text_color(0, 0, 0) # Black
        pdf.multi_cell(0, 8, question)
        pdf.ln(5)
        
        # Answer Section
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(76, 175, 80) # Assistant green
        pdf.cell(0, 10, "DocQuery Response:", ln=True)
        pdf.ln(2)
        
        # Reset color for the body text
        pdf.set_text_color(44, 62, 80) # Dark grey
        pdf.set_font("helvetica", "", 11)
        
        # fpdf2's write_html is limited but better than plain multi_cell
        # Pre-process Markdown to ensure lists are on new lines for the HTML parser
        processed_answer = re.sub(r'(\n\d+\.)', r'\n\1', answer) # Add extra break before numbered lists
        processed_answer = re.sub(r'(\n[*•-])', r'\n\1', processed_answer) # Add extra break before bullet lists
        
        html_answer = markdown.markdown(processed_answer, extensions=['tables'])
        
        # Clean up HTML for fpdf2 compatibility
        html_answer = html_answer.replace("<strong>", "<b>").replace("</strong>", "</b>")
        html_answer = html_answer.replace("<em>", "<i>").replace("</em>", "</i>")
        
        # Ensure <li> tags have line breaks after them if fpdf2 is grouping them
        html_answer = html_answer.replace("</li>", "</li><br>")
        
        # CRITICAL: fpdf2 DOES NOT support nested tags inside <td> or <th>
        def strip_nested_tags(match):
            cell_content = match.group(2)
            clean_content = re.sub(r'<[^>]+>', '', cell_content)
            return f"<{match.group(1)}>{clean_content}</{match.group(1)}>"
        
        html_answer = re.sub(r'<(td|th)>(.*?)</\1>', strip_nested_tags, html_answer, flags=re.DOTALL)
        
        # Render HTML
        pdf.write_html(html_answer)
        
        # Footer
        pdf.set_y(-15)
        pdf.set_font("helvetica", "I", 8)
        pdf.set_text_color(128, 128, 128)
        pdf.cell(0, 10, "Generated by DocQuery AI", align="C")
        
        return bytes(pdf.output(dest='S'))
